version: '3.8'

services:
  # Main application with different auth providers
  mcp-auth-local:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTH_PROVIDER=local
      - JWT_SECRET=local-dev-secret-change-in-production
      - REDIS_JWKS=true
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AWS Cognito example
  mcp-auth-aws:
    build: .
    ports:
      - "8001:8000"
    environment:
      - AUTH_PROVIDER=aws
      - PROVIDER_CONFIG={"cognito_region":"us-west-2","cognito_user_pool_id":"us-west-2_XXXXXXXXX","audience":"your-client-id"}
      - REDIS_JWKS=true
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  # Google OAuth2 example
  mcp-auth-google:
    build: .
    ports:
      - "8002:8000"
    environment:
      - AUTH_PROVIDER=google
      - PROVIDER_CONFIG={"audience":"your-client-id.apps.googleusercontent.com"}
      - REDIS_JWKS=true
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      - redis

  # GitHub OAuth2 example
  mcp-auth-github:
    build: .
    ports:
      - "8003:8000"
    environment:
      - AUTH_PROVIDER=github
      - PROVIDER_CONFIG={"client_id":"your_github_client_id","allowed_organizations":["your-org"]}
      - REDIS_JWKS=true
      - REDIS_URL=redis://redis:6379/3
    depends_on:
      - redis

  # Discord OAuth2 example
  mcp-auth-discord:
    build: .
    ports:
      - "8004:8000"
    environment:
      - AUTH_PROVIDER=discord
      - PROVIDER_CONFIG={"client_id":"your_discord_client_id","allowed_guilds":["123456789012345678"]}
      - REDIS_JWKS=true
      - REDIS_URL=redis://redis:6379/4
    depends_on:
      - redis

  # Enterprise multi-tenant example
  mcp-auth-enterprise:
    build: .
    ports:
      - "8005:8000"
    environment:
      - AUTH_PROVIDER=local
      - TENANT_STRATEGY=row_level_security
      - TENANT_RESOLVER=header
      - ENABLE_PERFORMANCE_MONITORING=true
      - ENABLE_COMPLIANCE_MONITORING=true
      - REDIS_URL=redis://redis:6379/5
    depends_on:
      - redis

  # Redis for JWKS caching and enterprise features
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp-auth-local
      - mcp-auth-aws
      - mcp-auth-google
      - mcp-auth-github
      - mcp-auth-discord
      - mcp-auth-enterprise

volumes:
  redis_data:
