name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit (format/lint)
        run: |
          pip install pre-commit
          # First run formatters to apply changes
          pre-commit run black --all-files || true
          pre-commit run isort --all-files || true
          # Then run linters which should pass
          pre-commit run ruff --all-files
          pre-commit run end-of-file-fixer --all-files || true
          pre-commit run trailing-whitespace --all-files || true
          pre-commit run check-yaml --all-files
      - name: Run unit tests
        run: pytest -q

  providers-integration:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install provider SDKs and dev deps
        run: |
          python -m pip install --upgrade pip
          # install provider SDKs directly to avoid building the package wheel (hatchling)
          pip install google-auth boto3
          # install redis/jwks runtime deps for provider integration tests
          pip install redis aioredis httpx
          pip install -r requirements-dev.txt
      - name: Run provider integration tests
        run: pytest tests/test_cloud_providers.py -q
