name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit (format/lint)
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Run unit tests
        run: pytest -q

  providers-integration:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install provider SDKs and dev deps
        run: |
          python -m pip install --upgrade pip
          # install provider SDKs directly to avoid building the package wheel (hatchling)
          pip install google-auth boto3 msal azure-identity
          pip install -r requirements-dev.txt
      - name: Run provider integration tests
        run: pytest tests/test_cloud_providers.py -q
